### ISSUE TITLE
Question: Do I still get credits for Approved and Merged PR's on September?

### ISSUE THREAD

**Issue by ThinkDevStudios** [thedevdojo/tails-components#125]
There was a bit of misunderstanding when I joined for HacktoberFest and started submitting PR's last September. I basically just relied on the video guide on DevDojo and started submitting it as soon as I have registered on HacktoberFest. I missed the submission timeline should be from October 1 to 30.  I think I was able to submit a total of 4 PR's that already got approved and merged. My question is do I still get credit for those 4?  I did submit another 2 PR's still waiting for approval but the other one got closed due to having similar title although is basically two different version. Hope to hear from you soon. Thank you!

**Comment by thinkverse** [comment]
Short answer, no. Long answer, kind of, it depends on if the PR's was submitted on September 30th and the date was October 1th in another timezone. As I understood it, sign-ups started about a week early, PR's made on October 1st in _ANY_ timezone counts. So if it's October 1st in one country, but September 30th where you are, those PR's submitted then would register on Hacktoberfest.

You can find all your registered PR's by login to your [Hacktoberfest profile]. 👍

[hacktoberfest profile]: https://hacktoberfest.digitalocean.com/login
