### ISSUE TITLE
Feature: Integration with Tailwind Play

### ISSUE THREAD

**Issue by dector** [thedevdojo/tails-components#210]
It would be nice to let users hack components on [Tailwind Play](https://play.tailwindcss.com/) in one click (e.g. creating sharable snippets by link might be enough for the first time).

**Comment by thinkverse** [comment]
I don't quite get this integration. 🤔&nbsp; Tails has its own [playground] already where users can write out their components before submitting them. Also, you can already share from Tailwind Play, it has a share button built-in?

[playground]: https://devdojo.com/tailwindcss/playground
