### ISSUE TITLE
Feature: Add Product Details page Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#241]
### Describe the solution you'd like

It would be great to have a product details component

### Additional context

If needed, here are some example designs:

https://www.pinterest.com/pin/500040364877595588/

**Comment by achimoraites** [comment]
Hello @bobbyiliev !
this looks interesting, can i take it ?

**Comment by omarkdev** [comment]
@bobbyiliev Please see #263

**Comment by Sayan-dev** [comment]
Hey @bobbyiliev, Can I work on this now?

**Comment by Priyanka11-dev** [comment]
Hey @bobbyiliev ,  would like to try this.
