### ISSUE TITLE
Feature: Add Shopping Cart page Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#242]
### Describe the solution you'd like

It would be great to have a shopping cart component

### Additional context

If needed, here are some example designs:

https://www.pinterest.com/pin/493003490463563155/

**Comment by wsameer** [comment]
@thinkverse  @bobbyiliev the Pinterest link doesn't work.
![image](https://user-images.githubusercontent.com/8468992/135612333-799872d9-183a-4f27-ab0c-b8e517ef855a.png)

**Comment by thinkverse** [comment]
Hmm, seems like it. You could always use Dribbble, Behance, or something similar for inspiration though.

**Comment by aakashraj01** [comment]
i would like to contribute plz assign me this @thinkverse
