### ISSUE TITLE
Feature: Add Checkout page Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#243]
### Describe the solution you'd like

It would be great to have a checkout component

### Additional context

If needed, here are some example designs:

https://www.pinterest.com/pin/323837029456659786/

**Comment by k-guy-dev** [comment]
Hey @bobbyiliev ! I've created a pull request for this issue, here's the link https://github.com/thedevdojo/tails/pull/255.

**Comment by Sayan-dev** [comment]
Working on it
