### ISSUE TITLE
Feature: Add User Profile Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#244]
### Describe the solution you'd like

It would be great to have a user profile page component

### Additional context

If needed, here are some example designs:

https://www.pinterest.com/pin/106608716166523709/

**Comment by k-guy-dev** [comment]
hey @bobbyiliev ! I've created a pull request for this issue. https://github.com/thedevdojo/tails/pull/254 . Please can you have a look. Thanks

**Comment by sivantha96** [comment]
does this still count for hacktoberfest 2021?

**Comment by thinkverse** [comment]
> does this still count for hacktoberfest 2021?

Yes, any PR that's made between Oct 1 and Oct 31 will count as long as it follows the rules set forth by the organizers.

The rules can be found on the landing page off Hacktoberfests [website](https://hacktoberfest.digitalocean.com/) near the bottom.

**Comment by sivantha96** [comment]
@thinkverse  Would you update the link to the example design and assign this to me? I could work on this.
