### ISSUE TITLE
Feature: Add Floating Menu Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#245]
### Describe the solution you'd like

It would be great to have a floating menu component

### Additional context

If needed, here are some example designs:

![leFkGvSlWn](https://user-images.githubusercontent.com/21223421/96689309-e860ba80-138a-11eb-9567-1db17c8d2b1a.gif)

**Comment by Omkar845** [comment]
i would like to contribute plz assign me this

**Comment by Sayan-dev** [comment]
If this is an enhancement, is this related to any previously built component?
