### ISSUE TITLE
Feature: add search for the components

### ISSUE THREAD

**Issue by kissu** [thedevdojo/tails-components#266]
### Is your feature request related to a problem? Please describe.

The components looks really clean and awesome ! But why isn't there a search fields to find some of them by typing let's say "dropdown".

### Describe the solution you'd like

Usual algolia or even more basic search field. Example: https://tailwindcomponents.com/search?query=dropdown

### Describe alternatives you've considered

Make a script to `load more` til the end and then make a dumb `ctrl + f`.

**Comment by thinkverse** [comment]
Awesome idea to add, sadly Tails will probably not receive any platform updates anymore.
