### ISSUE TITLE
Add Registration Form Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#3]
Hi there, 

It will be great to expand this awesome collection by adding a **Registration Form Tailwind CSS component**.

Hopefully, someone might be up for the challenge 🙌

**Comment by ryuk156** [comment]
i would like to work on this

**Comment by Draco9421** [comment]
Hey There!
This time added a registration form using TailwindCSS, Hope you like it this time.
