### ISSUE TITLE
Feature: Add a Feedback Form Tailwind CSS component.

### ISSUE THREAD

**Issue by VaishnaviNandakumar** [thedevdojo/tails-components#312]
### Is your feature request related to a problem? Please describe.
I'd like to contribute to a Feedback Form Tailwind CSS component.

### Describe the solution you'd like
A questionnaire form with choices in the form of radio buttons and possibly a text input for further suggestions.

### Additional context
I wanted to know if this contribution would be a valid component before proceeding with it. I could not find an existing component with the same context so do let me know if there are any suggestions I could keep in mind before starting or if there's anything I've overlooked that would make this component invalid. Thanks!

**Comment by aakashraj01** [comment]
i would like to contribute .Can You assign me this work ?

**Comment by VaishnaviNandakumar** [comment]
I'm not responsible for that. I raised the issue because I want to contribute to this feature if possible.

**Comment by VaishnaviNandakumar** [comment]
Hi @thinkverse ! Can I proceed with this feature?
