### ISSUE TITLE
Animated Submit Button

### ISSUE THREAD

**Issue by shreyasd302** [thedevdojo/tails-components#355]
[
![output](https://user-images.githubusercontent.com/69694647/138590112-460182cd-1d7c-4b03-81ba-400c91980b41.jpg)
](url)

**Comment by shreyasd302** [comment]
Can I work on this?

**Comment by bobbyiliev** [comment]
As Hacktoberfest is already over, I am going to close this issue.
For more information about the upcoming changes, I would recommend keeping an eye on the [DevDojo](https://devdojo.com/tails) website! 🙂
