### ISSUE TITLE
Bug: Subscription Handling

### ISSUE THREAD

**Issue by heymartinadams** [thedevdojo/tails-components#366]
### Subscription Cancellation

When a user wishes to cancel their subscription, please keep the subscription going until the end of the period for which the user has subscribed (the user paid for that period, after all).

![CleanShot 2022-02-18 at 10 19 00@2x](https://user-images.githubusercontent.com/11673745/154740115-86f39bec-5af0-4f94-b6ba-0130108340e2.png)

To make the user choose between either cancelling immediately, or wait until a moment that’s closer to the renewal period effectively disables what the user paid for:

1. if they cancel immediately, they lose out on the remainder of their paid period;
2. if they wait, they risk being charged another time since it’s not clear that you will notify users with ample time _prior_ to subscription renewal.

**Comment by thinkverse** [comment]
This issue is neither a bug nor an issue related to the open source tails version.

I will forward your issue of DevDojos subscription model to the platform creators, but this issue will be closed.
