### ISSUE TITLE
Add Contact Form Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#4]
Hi there, 

It will be great to expand this awesome collection by adding a **Contact Form Tailwind CSS component**.

Hopefully, someone might be up for the challenge 🙌

**Comment by kubeden** [comment]
Hey, working on it!

**Comment by shades-7** [comment]
i will work on it

**Comment by cosmoimai** [comment]
sir, can I work on it?

**Comment by akash2408** [comment]
Hie there,
i recently added a contact form please give a look

**Comment by cosmoimai** [comment]
done sir, #184
