### ISSUE TITLE
Feature: Better Component Organization

### ISSUE THREAD

**Issue by nahtnam** [thedevdojo/tails-components#42]
### Is your feature request related to a problem? Please describe.

Hello! First off, I want to say I love the components and everything about it! I just find that discovering the components is a bit hard. Is it possible to implement some sort of category system such as tailwindui.com?

### Describe the solution you'd like

Categorize by type such as Header, Footer, CTA, raw components (alert, buttons), etc

### Describe alternatives you've considered

N/A

### Additional context

https://kitwind.io/products/kometa/components
https://tailwindui.com/components

Thanks again!

**Comment by tnylea** [comment]
Hey @nahtnam, absolutely. I was going to add a filter button where you could filter the results based on CTA, FAQ, header etc. I would like to get a few more components implemented before adding the filter, but I may work on it sooner than later 👍 

Wow! I hadn't seen kitwind before, looks like a really cool project. I'll have to look to them for some inspiration. I'll keep you posted with filtering functionality has been added 😄

**Comment by thinkverse** [comment]
This is unlikely to happen so I'm closing this issue.
