### ISSUE TITLE
Feature: Add Newsletter Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#48]
Hi there,

It will be great to expand this awesome collection by adding a **Newsletter** Tailwind CSS component.

Hopefully, someone might be up for the challenge 🙌

**Comment by pranav2012** [comment]
Hey @bobbyiliev, Would love to contribute please let me know a little more about the component so I can start working on it thanks

**Comment by thinkverse** [comment]
I'm with @pranav2012, is this supposed to be a simple **Newsletter** input component? Like _Sign up for our newsletter here_, or the actual **Newsletter** email that's sent out? 🤔

**Comment by bobbyiliev** [comment]
Hey @thinkverse and @pranav2012 

Ah yes good point! Just a simple Newsletter input component is what I had in mind.

However, if anyone is filling adventurous an actual Newsletter mail would be awesome as well 🙌

**Comment by pranav2012** [comment]
ok, @bobbyiliev started working on this @thinkverse what's say if one of us works on the UI and the other on sending a mail? you up for this?

**Comment by mohitn787** [comment]
Hi @bobbyiliev, I would also love to contribute to this project and help you out with any way you want , please let me know any specific add-on that you are looking forward to.

**Comment by pranav2012** [comment]
Hey @bobbyiliev just completed shall I make a pull request, please merge after 1st October so it can be counted in Hackctober fest & please assign me with this issue, Thank You :smile:

**Comment by thinkverse** [comment]
> please merge after 1st October so it can be counted in Hackctober...

Sadly that does count, only pull request made after or on October 1 count.

**Comment by pranav2012** [comment]
Will make after 1st then thanks 😊

**Comment by imsaptarshi** [comment]
I would like to contribute to this!

**Comment by bobbyiliev** [comment]
Closed by #59
