### ISSUE TITLE
Add Product List Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#5]
Hi there, 

It will be great to expand this awesome collection by adding a **Product List Tailwind CSS component**.

Hopefully, someone might be up for the challenge 🙌

**Comment by rishabkumar7** [comment]
@bobbyiliev Should I create the PR now? or wait till 1st Oct to be considered for Hacktoberfest?

**Comment by tanya4067** [comment]
Hey , I'd like to contribute

**Comment by rishabkumar7** [comment]
Created PR - https://github.com/thedevdojo/tails/pull/99

**Comment by KaranBajaj594** [comment]
can i work on it?

**Comment by thinkverse** [comment]
> can i work on it?

Assigned. 👍

**Comment by KaranBajaj594** [comment]
Thank you for your response.... working on it

**Comment by KaranBajaj594** [comment]
Done with the work . I have made a pull request.
Please check .
