### ISSUE TITLE
Add Notification Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#6]
Hi there, 

It will be great to expand this awesome collection by adding a **Notification Tailwind CSS component**.

Hopefully, someone might be up for the challenge 🙌

**Comment by pandurijal** [comment]
Hello, I am interested to take this issue. But I bit confused here, what kind of notification you mean here? What's the difference between this and the alert component that you already have?

**Comment by bobbyiliev** [comment]
The project now has `notification-simple.html` so closing this issue! 🙌
