### ISSUE TITLE
Add Pricing Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#7]
Hi there, 

It will be great to expand this awesome collection by adding a **Pricing Tailwind CSS component**.

Hopefully, someone might be up for the challenge 🙌

**Comment by KushalBhanot** [comment]
Hey! I would like to work on this issue.

**Comment by kubeden** [comment]
Hey There,

I just submitted a clean pricing component 😊😊 I hope you like it!

**Comment by mk-singhal** [comment]
hi @bobbyiliev ,
Is this issue still open , if so i want to work on it, please assign it to me !!

**Comment by Draco9421** [comment]
Hey There,
I recently added a new price component.

**Comment by thinkverse** [comment]
We currently have two different pricing components in Tails, with another currently under review. Should we close this issue or keep it open @bobbyiliev?

**Comment by bobbyiliev** [comment]
Yes, thanks for pointing that out @thinkverse 🙌
