### ISSUE TITLE
Add Alerts Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#8]
Hi there, 

It will be great to expand this awesome collection by adding an **Alerts Tailwind CSS component** similar to what Bootstrap offers:

https://getbootstrap.com/docs/4.5/components/alerts/

Hopefully, someone might be up for the challenge 🙌

**Comment by danielebarbaro** [comment]
hi, I made a PR 🤓

**Comment by imsaptarshi** [comment]
I would be doing this!

**Comment by bobbyiliev** [comment]
Fixed by #56
