### ISSUE TITLE
Add Pagination Tailwind CSS Component

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/tails-components#9]
Hi there, 

It will be great to expand this awesome collection by adding a **Pagination Tailwind CSS component**.

Hopefully, someone might be up for the challenge 🙌

**Comment by rcode321** [comment]
can i work on this issue?

**Comment by ryuk156** [comment]
i would like to work on this issue

**Comment by bobbyiliev** [comment]
Hi @rcode321 amd @ryuk156 

As @rcode321 claimed the issue first, please feel free to start working on it! Looking forward to your PR 🙌

@ryuk156 Feel free to grab some of the other issues or submit a new suggestion! 👏

**Comment by rcode321** [comment]
Hi @Bobby thanks for the response, i think this open issue was
already merged and closed, cause i already added the pagination components.
may i know if we can work again in this issue? thanks

**Comment by bobbyiliev** [comment]
Hi @rcode321 yes you are right, this can be closed now! Thanks for your contribution 🐱‍💻
